### PR TITLE
Checks the status of the process. 

### PR DESCRIPTION
**Pull request by DonRichards**
This checks the progress and validity of the file structure. 
Has some commented out code (has not been tested)

### CODE REVIEW

**Review by pc37utn — COMMENTED** [review]
It would be nice to still have the choice of output OBJ. 
Maybe don't lock it down one way or the other.

**Review by pc37utn — COMMENTED** [review]
Unsure what the "known bug" at the bottom is, will be glad to test this soon.

**Review by pc37utn — COMMENTED** [review]
cannot rename the '-' to '_', those are necessary.

**Review by pc37utn — APPROVED** [review]
Too many changes and lines of code to read and test individually.  Merging so all of it can be tested.

**Comment by markpbaggett** [comment]
@DonRichards and @pc37utn, please tell me we are not merging code that has not been tested.  After multiple instances of doing this in the last two weeks have we not yet learned?

Also, @DonRichards.  I just had a conversation with you yesterday that you initiated where you told me that we needed to stop opening massive pull requests, yet this pull request is more than double the size of the original repository.

Finally, I was told last year that we couldn't have a pull request that did not have a JIRA ticket or tickets.  Where are these?

**Pull request merged**
