### PR TITLE
Addresses TRAC-1136

### PR DESCRIPTION
**Pull request by DonRichards**
** JIRA Ticket**: https://jira.lib.utk.edu/browse/TRAC-1136

# What does this Pull Request do?

* it asks for user input for the working directory(where stuff needs to be processed), the image folder and the metadata folder. 
* it creates a config file with these 3 values in it so it can be stopped and resumed at any time.
* it copies data into the working directory for processing
* creates a multi-thread behavior for the bookprep process
  * it limits the screen sessions to only run 100 at a time
* it moves files to a staging folder when it completes
* upon completion it removes the folder it added to the working directory (book_processing) and the config file

# What's new?
This wrapper multi-threads bookprep.php and improves the prep speed

# How should this be tested?
run bookprep.sh and point it to the appropriate directories. Please use process directory to /gwork/USERNAME. It will create a new folder there and it should copy all of the file into this directory and run bookprep against it. It should also show you the progress and alert you if there is any missing files. It should not proceed to the next "STEP" if there are and errors or missing files. 

# Additional Notes:
n/a 

# Interested parties
Tag (@ mention) interested parties or, if unsure, @utkdigitalinitiatives/digital-initiatives-developers

### CODE REVIEW

**Comment by pc37utn** [comment]
I can't do any thing about this pull request until I have reversed the last 2.

**Comment by DonRichards** [comment]
I think I found an issue. One moment.

**Comment by DonRichards** [comment]
@pc37utn If you need me to do it I can.

**Comment by DonRichards** [comment]
@pc37utn Merging this should fix the last merge.

**Pull request closed without merging**
